# Generated by Django 2.2.2 on 2019-06-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScienceLab_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical', to='ScienceLab_app.Formula')),
            ],
        ),
    ]
